server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: 119.23.109.182
    port: 5672
    username: ymy
    password: ymy
    virtual-host: YmyTest
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
